
package com.asac.fundtransferinquiry;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceAction", targetNamespace = "urn:FundTransferInquiry", wsdlLocation = "file:/D:/My%20Application/WebTest/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/FundTransferInquiry.wsdl")
public class ServiceAction
    extends Service
{

    private final static URL SERVICEACTION_WSDL_LOCATION;
    private final static WebServiceException SERVICEACTION_EXCEPTION;
    private final static QName SERVICEACTION_QNAME = new QName("urn:FundTransferInquiry", "ServiceAction");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/My%20Application/WebTest/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/FundTransferInquiry.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEACTION_WSDL_LOCATION = url;
        SERVICEACTION_EXCEPTION = e;
    }

    public ServiceAction() {
        super(__getWsdlLocation(), SERVICEACTION_QNAME);
    }

    public ServiceAction(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEACTION_QNAME, features);
    }

    public ServiceAction(URL wsdlLocation) {
        super(wsdlLocation, SERVICEACTION_QNAME);
    }

    public ServiceAction(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEACTION_QNAME, features);
    }

    public ServiceAction(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceAction(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicePort
     */
    @WebEndpoint(name = "ServicePort")
    public ServicePort getServicePort() {
        return super.getPort(new QName("urn:FundTransferInquiry", "ServicePort"), ServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePort
     */
    @WebEndpoint(name = "ServicePort")
    public ServicePort getServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:FundTransferInquiry", "ServicePort"), ServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEACTION_EXCEPTION!= null) {
            throw SERVICEACTION_EXCEPTION;
        }
        return SERVICEACTION_WSDL_LOCATION;
    }

}
