
package com.asac.fundtransferinhousesingle;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FundTransferInHouseSingleService", targetNamespace = "urn:FundTransferInHouseSingle", wsdlLocation = "file:/D:/PROJECT/Pak_Indra/workspace/ASAC/src/conf/xml-resources/web-services/FundTransferInHouseSingle/wsdl/FundTransferInHouseSingle.wsdl")
public class FundTransferInHouseSingleService
    extends Service
{

    private final static URL FUNDTRANSFERINHOUSESINGLESERVICE_WSDL_LOCATION;
    private final static WebServiceException FUNDTRANSFERINHOUSESINGLESERVICE_EXCEPTION;
    private final static QName FUNDTRANSFERINHOUSESINGLESERVICE_QNAME = new QName("urn:FundTransferInHouseSingle", "FundTransferInHouseSingleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/PROJECT/Pak_Indra/workspace/ASAC/src/conf/xml-resources/web-services/FundTransferInHouseSingle/wsdl/FundTransferInHouseSingle.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FUNDTRANSFERINHOUSESINGLESERVICE_WSDL_LOCATION = url;
        FUNDTRANSFERINHOUSESINGLESERVICE_EXCEPTION = e;
    }

    public FundTransferInHouseSingleService() {
        super(__getWsdlLocation(), FUNDTRANSFERINHOUSESINGLESERVICE_QNAME);
    }

    public FundTransferInHouseSingleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ServicePort
     */
    @WebEndpoint(name = "FundTransferInHouseSinglePort")
    public ServicePort getFundTransferInHouseSinglePort() {
        return super.getPort(new QName("urn:FundTransferInHouseSingle", "FundTransferInHouseSinglePort"), ServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePort
     */
    @WebEndpoint(name = "FundTransferInHouseSinglePort")
    public ServicePort getFundTransferInHouseSinglePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:FundTransferInHouseSingle", "FundTransferInHouseSinglePort"), ServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FUNDTRANSFERINHOUSESINGLESERVICE_EXCEPTION!= null) {
            throw FUNDTRANSFERINHOUSESINGLESERVICE_EXCEPTION;
        }
        return FUNDTRANSFERINHOUSESINGLESERVICE_WSDL_LOCATION;
    }

}
